[window]
opacity = 0.95
dynamic_padding = true
dimensions = { columns = 100, lines = 30 }


[colors.primary]
foreground = "#cccccc"
background = "#333333"


[cursor]
style.blinking = "On"
blink_interval = 500
blink_timeout = 15


[mouse]
hide_when_typing = true

[font]
normal={ family="Jetbrains Mono", style="Regular" }
bold={ style="Bold" }
italic={ style="Italic" }
bold_italic={ style="Bold Italic" }
