#!/usr/bin/env bash

packages="hyprpaper"

config="hypr/hyprpaper.conf"


function post_install() {
    if [ -z "$EXTRAS_DIR" ] || [ ! -d "$EXTRAS_DIR" ]; then
        exit_with_err "\$EXTRAS_DIR is not set or is not a directory"
    fi

    copy $EXTRAS_DIR/images/Lake.jpg $HOME/Pictures/wallpapers/Lake.jpg
    copy $EXTRAS_DIR/images/Mountain.jpg $HOME/Pictures/wallpapers/Mountain.jpg
}
