#!/usr/bin/env bash

dependencies="hypr/hypridle hypr/hyprlock hypr/hyprpaper waybar"
packages="hyprland hyprland-protocols hyprpolkitagent"

config="hypr/hyprland.conf"
scripts="hypr/import_env.sh,hypr/record.sh,wmenu/logout.sh"
