#!/usr/bin/env bash

dependencies=""
packages="alacritty"

config="alacritty/alacritty.toml"


function install_config() {
    if [ -z "$CONFIG_DIR" ] || [ ! -d "$CONFIG_DIR" ]; then
        exit_with_err "\$CONFIG_DIR is not set or is not a directory"
    fi

    install -Dm644 $CONFIG_DIR/alacritty/alacritty.toml $HOME/.config/alacritty/alacritty.toml
}

