#!/usr/bin/env bash

dependencies=""
packages="discord"


function install_config() {
    cfg_file="$HOME/.config/discord/settings.json"
    new_cfg=$(cat $cfg_file | jq '. += { SKIP_HOST_UPDATE: true, DANGEROUS_ENABLE_DEVTOOLS_ONLY_ENABLE_IF_YOU_KNOW_WHAT_YOURE_DOING: true }')
    printf "$new_cfg" > $cfg_file
}
