#!/usr/bin/env bash

dependencies=""
packages="discord"


function manual_config() {
    cfg_file="$XDG_CONFIG_HOME/discord/settings.json"
    new_cfg=$(cat $cfg_file | jq '. += { SKIP_HOST_UPDATE: true, DANGEROUS_ENABLE_DEVTOOLS_ONLY_ENABLE_IF_YOU_KNOW_WHAT_YOURE_DOING: true }')
    printf "$new_cfg" > $cfg_file
}
