#!/usr/bin/env bash

dependencies=""
packages="fuzzel"

config="fuzzel/fuzzel.ini"


function install_config() {
    if [ -z "$CONFIG_DIR" ] || [ ! -d "$CONFIG_DIR" ]; then
        exit_with_err "\$CONFIG_DIR is not set or is not a directory"
    fi

    install -Dm644 $CONFIG_DIR/fuzzel/fuzzel.ini $HOME/.config/fuzzel/fuzzel.ini
}
