#!/usr/bin/env bash

dependencies="waybar"
packages="hyprland hyprland-protocols hyprpaper hypridle hyprlock hyprpolkitagent"

config="hypr/hyprland.conf,hypr/hyprpaper.conf,hypr/hypridle.conf,hypr/hyprlock.conf"


function post_install() {
    if [ -z "$EXTRAS_DIR" ] || [ ! -d "$EXTRAS_DIR" ]; then
        exit_with_err "\$EXTRAS_DIR is not set or is not a directory"
    fi

    copy $EXTRAS_DIR/images/Lake.jpg $HOME/Pictures/wallpapers/Lake.jpg
    copy $EXTRAS_DIR/images/Mountain.jpg $HOME/Pictures/wallpapers/Mountain.jpg

    copy $EXTRAS_DIR/scripts/hypr/import_env.sh $HOME/scripts/hypr/import_env.sh
    copy $EXTRAS_DIR/scripts/hypr/record.sh $HOME/scripts/hypr/record.sh
    copy $EXTRAS_DIR/scripts/wmenu/logout.sh $HOME/scripts/wmenu/logout.sh
    chmod 755 $HOME/scripts/hypr/import_env.sh $HOME/scripts/hypr/record.sh $HOME/scripts/wmenu/logout.sh
}
