#!/usr/bin/env bash

dependencies=""
packages="lemurs"

config="lemurs/config.toml:/etc/lemurs/config.toml"


function install_config() {
    if [ -z "$CONFIG_DIR" ] || [ ! -d "$CONFIG_DIR" ]; then
        exit_with_err "\$CONFIG_DIR is not set or is not a directory"
    fi

    if ! diff $CONFIG_DIR/lemurs/config.toml /etc/lemurs/config.toml; then
        sudo install -Dm644 $CONFIG_DIR/lemurs/config.toml /etc/lemurs/config.toml
    fi
}
