#!/usr/bin/env bash

dependencies="hypr/hypridle hypr/hyprlock hypr/hyprpaper mako waybar"
packages="niri hyprpolkitagent xdg-desktop-portal-gtk xdg-desktop-portal-gnome xwayland-satellite"

config="niri/config.kdl"
scripts="hypr/import_env.sh,wmenu/logout.sh"
