#!/usr/bin/env bash

dependencies="hypr/hypridle hypr/hyprlock hypr/hyprpaper mako waybar"
packages="niri hyprpolkitagent xdg-desktop-portal-gtk xdg-desktop-portal-gnome xwayland-satellite"

config="niri/config.kdl"
scripts="hypr/import_env.sh,niri/lock.sh,niri/focus_or_spawn.sh,niri/select_window.sh,wmenu/logout.sh"


function post_install() {
    mkdir -p ~/.local/share/icons

    curl -s https://site-assets.fontawesome.com/releases/v7.2.0/svgs-full/solid/arrow-right-from-bracket.svg -o ~/.local/share/icons/logout.svg
    curl -s https://site-assets.fontawesome.com/releases/v7.2.0/svgs-full/solid/lock.svg -o ~/.local/share/icons/lock.svg
    curl -s https://site-assets.fontawesome.com/releases/v7.2.0/svgs-full/solid/power-off.svg -o ~/.local/share/icons/power.svg
    curl -s https://site-assets.fontawesome.com/releases/v7.2.0/svgs-full/solid/arrows-rotate.svg -o ~/.local/share/icons/reboot.svg
    curl -s https://site-assets.fontawesome.com/releases/v7.2.0/svgs-full/solid/microchip.svg -o ~/.local/share/icons/uefi.svg

    sed -i 's|fill="[^"]*"|fill="#eeeeee"|' \
        ~/.local/share/icons/logout.svg \
        ~/.local/share/icons/lock.svg \
        ~/.local/share/icons/power.svg \
        ~/.local/share/icons/reboot.svg \
        ~/.local/share/icons/uefi.svg

    sed -i 's|<path d|<path fill="#eeeeee" d|' \
        ~/.local/share/icons/logout.svg \
        ~/.local/share/icons/lock.svg \
        ~/.local/share/icons/power.svg \
        ~/.local/share/icons/reboot.svg \
        ~/.local/share/icons/uefi.svg
}
