#!/usr/bin/env bash

dependencies="dev/base dev/rp2040"


function post_install() {
    mkdir -p $HOME/projects

    git clone git@github.com:Cameron-Reed1/macrolink.git $HOME/projects/macrolink
    git clone git@github.com:Cameron-Reed1/Macropad.git $HOME/projects/Macropad
    git clone git@github.com:Cameron-Reed1/Cpp-Argument-Parser.git $HOME/projects/Cpp-Argument-Parser
    git clone git@github.com:Cameron-Reed1/Zig-Argument-Parser.git $HOME/projects/Zig-Argument-Parser
}
