#!/usr/bin/env bash

dependencies=""
packages="openssh"


function post_install() {
    if [ ! -f "$HOME/.ssh/id_ed25519" ]; then
        ssh-keygen -t ed25519 -f "$HOME/.ssh/id_ed25519" -N ""
    fi

    cat "$HOME/.ssh/id_ed25519.pub"
}
