#!/usr/bin/env bash

dependencies=""
packages="tailscale"


function manual_config() {
    if [ "$(tailscale status)" != "Logged out." ]; then
        printf "Skipping tailscale config\n"
        return
    fi

    sudo tailscale login --qr --nickname=home --accept-routes --login-server=https://scale.cam123.dev:443
    sudo tailscale up
}
