#!/usr/bin/env bash

dependencies=""
packages="tlp"


function post_install() {
    if [ "$(systemctl is-enabled systemd-rfkill.socket)" != "masked" ]; then
        sudo systemctl mask systemd-rfkill.socket
    fi

    if [ "$(systemctl is-enabled systemd-rfkill.service)" != "masked" ]; then
        sudo systemctl mask systemd-rfkill.service
    fi

    if ! systemctl is-enabled tlp.service > /dev/null; then
        sudo systemctl start tlp.service
    fi
}
