#!/usr/bin/env bash

dependencies=""
packages=""

config="udev/50-adafruit.rules:/etc/udev/rules.d/50-adafruit.rules,udev/50-arduino.rules:/etc/udev/rules.d/50-arduino.rules,udev/50-nrf.rules:/etc/udev/rules.d/50-nrf.rules,udev/51-esp.rules:/etc/udev/rules.d/51-esp.rules"
