#!/usr/bin/env bash

dependencies="fastfetch newsboat reflector"
packages="ncdu"


function manual_install() {
    install_aur_pkg dashbinsh
    install_aur_pkg mkinitcpio-numlock
}

function manual_config() {
    if ! grep -q "^HOOKS=.*[( ]numlock[ )]" /etc/mkinitcpio.conf; then
        sudo sed -i 's/\(^HOOKS=(.*consolefont\)\(.*\)/\1 numlock\2/' /etc/mkinitcpio.conf
        sudo mkinitcpio -P
    fi
}
