#!/usr/bin/env bash

dependencies=""
packages="base-devel clang cmake gcc git go lld llvm make ninja rustup zig"


function post_install() {
    if [ "$(rustup toolchain list)" = "no installed toolchains" ]; then
        rustup default stable
    fi
}

function install_config() {
    if [ -z "$CONFIG_DIR" ] || [ ! -d "$CONFIG_DIR" ]; then
        exit_with_err "\$CONFIG_DIR is not set or is not a directory"
    fi

    install -Dm644 $CONFIG_DIR/pycodestyle $HOME/.config/pycodestyle
    install -Dm644 $CONFIG_DIR/zls.json $HOME/.config/zls.json
}
