#
# $ZDOTDIR/.zshenv
#


# Copied from arch linux's default /etc/profile
function append_path() {
    [ ! -d "$1" ] && return
    case ":$PATH:" in
        *:"$1":*)
            ;;
        *)
            PATH="${PATH:+$PATH:}$1"
    esac
}


append_path "$HOME/.local/bin"
append_path "$HOME/go/bin"


export PATH
unset -f append_path



EDITOR="vim"
if command -v nvim > /dev/null; then
    EDITOR="nvim"
fi

export EDITOR

