#
# $ZDOTDIR/.zshenv
#


if [ -d /opt/devkitpro ]; then
    export DEVKITPRO=/opt/devkitpro
    export DEVKITARM=$DEVKITPRO/devkitARM
    export DEVKITPPC=$DEVKITPRO/devkitPPC
fi

if [ -d $HOME/.local/share/esp ]; then
    export IDF_TOOLS_PATH=$HOME/.local/share/esp/idf
fi


export ZVM_PATH="${XDG_DATA_HOME:-$HOME/.local/share}/zvm"



# Copied from arch linux's default /etc/profile
function append_path() {
    [ ! -d "$1" ] && return
    case ":$PATH:" in
        *:"$1":*)
            ;;
        *)
            PATH="${PATH:+$PATH:}$1"
    esac
}


append_path "/home/cameron/.local/share/JetBrains/Toolbox/scripts"
append_path "$HOME/.local/bin"
append_path "$HOME/.config/emacs/bin"
append_path "$HOME/go/bin"
append_path "$ZVM_PATH/bin"


export PATH
unset -f append_path



EDITOR="vim"
if command -v nvim > /dev/null; then
    EDITOR="nvim"
fi

export EDITOR

