#!/usr/bin/env bash


function manual_install() {
    if [ -z "$SETUP_DIR" ] || [ ! -d "$SETUP_DIR" ]; then
        exit_with_err "\$SETUP_DIR is not set or is not a directory"
    fi

    if [ -z "$COMPONENT_DIR" ] || [ ! -d "$COMPONENT_DIR" ]; then
        exit_with_err "\$COMPONENT_DIR is not set or is not a directory"
    fi

    if [ ! -f "$SETUP_DIR/manage.sh" ]; then
        exit_with_err "$SETUP_DIR/manage.sh is missing!"
    fi


    src=$(realpath "$SETUP_DIR/manage.sh")
    dest="$HOME/.local/bin/script"


    if [ -f "$dest" ]; then
        printf "Not installing script symlink to manage.sh because $dest already exists\n"
        return 1
    fi

    if [ -L "$dest" ]; then
        if [ "$(realpath $dest)" = "src" ]; then # Symlink already points to the correct location
            return 0
        fi

        if [ -e "$(realpath $dest)" ]; then
            printf "Not installing script symlink to manage.sh because $dest already exists\n"
            return 1
        fi
    fi

    ln -s "$src" "$dest"
}
